### ISSUE TITLE
Entities to Bacnet Objects

### ISSUE THREAD

**Issue by wamber2011** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#17]
Hi, my issue has only just started after working just fine for the last 3 weeks or so.

**Describe the bug**
I deleted everything relating to the interface and add in; as I was having trouble with the "entities to bacnet objects" I was using "number" "switch" and "sensor" and then when starting from the beginning again - as soon as I add these entities the Bacnet service crashes. I can discover devices in HA but only when the entities line  in the service configuration is blank.

![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/156784122/80ce8f89-3076-43cb-9515-6b4c8253400e)

-----------------------------------------------------------
 Add-on: Bepacom BACnet/IP Interface
 Bepacom BACnet/IP interface for the Bepacom EcoPanel. Allows BACnet/IP devices to be available to Home Assistant through an API.
-----------------------------------------------------------
 Add-on version: 1.3.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.0  (aarch64 / green)
 Home Assistant Core: 2024.2.4
 Home Assistant Supervisor: 2024.02.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-interface: starting
[15:09:53] INFO: Running init-nginx.
[15:09:53] INFO: Running init-interface.
[15:09:53] INFO: Allowed addresses for NGINX: 127.0.0.1 192.168.1.23 172.30.232.1 172.30.32.1
[15:09:54] INFO: Generated ingress configuration successfully!
s6-rc: info: service init-nginx successfully started
[BACpypes]
objectName: EcoPanel
address: 192.168.1.23/24
objectIdentifier: 4069
maxApduLengthAccepted: 1476
segmentation: segmentedBoth
vendorIdentifier: 15
foreignBBMD: -
foreignTTL: 255
maxSegmentsAccepted: 64
loglevel: INFO
defaultPriority: 9
updateInterval: 600
s6-rc: info: service init-interface successfully started
s6-rc: info: service interface: starting
s6-rc: info: service interface successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[15:09:54] INFO: Running interface
s6-rc: info: service legacy-services successfully started

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/bin/main.py", line 315, in main
    object_manager = ObjectManager(
                     ^^^^^^^^^^^^^^
  File "/usr/bin/BACnetIOHandler.py", line 919, in __init__
    self.add_object(object_type="analogValue", index=index, entity=data)
  File "/usr/bin/BACnetIOHandler.py", line 1101, in add_object
    friendly_name = entity["attributes"].get("friendly_name")
                    ~~~~~~^^^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/bacpypes3/ipv4/__init__.py", line 155, in set_local_transport_protocol
    transport, protocol = task.result()
                          ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1438, in create_datagram_endpoint
    await waiter
asyncio.exceptions.CancelledError
ERROR:    An uncaught error occurred: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/bin/main.py", line 315, in main
    object_manager = ObjectManager(
                     ^^^^^^^^^^^^^^
  File "/usr/bin/BACnetIOHandler.py", line 919, in __init__
    self.add_object(object_type="analogValue", index=index, entity=data)
  File "/usr/bin/BACnetIOHandler.py", line 1101, in add_object
    friendly_name = entity["attributes"].get("friendly_name")
                    ~~~~~~^^^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/bacpypes3/ipv4/__init__.py", line 186, in set_broadcast_transport_protocol
    transport, protocol = task.result()
                          ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1438, in create_datagram_endpoint
    await waiter
asyncio.exceptions.CancelledError
Traceback (most recent call last):
  File "/usr/bin/main.py", line 388, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/bin/main.py", line 315, in main
    object_manager = ObjectManager(
                     ^^^^^^^^^^^^^^
  File "/usr/bin/BACnetIOHandler.py", line 919, in __init__
    self.add_object(object_type="analogValue", index=index, entity=data)
  File "/usr/bin/BACnetIOHandler.py", line 1101, in add_object
    friendly_name = entity["attributes"].get("friendly_name")
                    ~~~~~~^^^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable
[15:10:04] INFO: Service BACnet Interface exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[15:10:04] INFO: Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service interface: stopping
s6-rc: info: service interface successfully stopped
s6-rc: info: service init-interface: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service init-interface successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Bepacom-Raalte** [comment]
My apologies, seems my description of entities is a little unclear. To add an entity, you have to write down the full specific entity ID.

![afbeelding](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/126168314/ce09f5fc-2439-4bd9-90d2-34b7a9ce4253)

**Comment by wamber2011** [comment]
Ahh I get it now. thankyou, I was interpreting it a different way...thankyou

Just learning HA... Now I need to make a slider toggle for a bacnet AV 0-100% for lighting.

![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/156784122/7f57cbd5-dc0f-4e0b-b2d4-be7e2cd273b0)

**Comment by Bepacom-Raalte** [comment]
Do you want a slider you can set through Home Assistant or through BACnet?

**Comment by wamber2011** [comment]
I need one for my lighting points that are actually Bacnet AO.  (from 0 to 100 % in 10% or 5% increments) Dali lighting.
I am reading and reading about HA. I am going through the learning curve.
looking at the below, just want simple slider for the AO I am using.
https://github.com/thomasloven/lovelace-slider-entity-row

**Comment by Bepacom-Raalte** [comment]
So to use it, you have to install this card to your Home Assistant.
Then, following the quick start on that repository, you can add it to your dashboard.

![afbeelding](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/126168314/7f53b4ed-a5dd-4012-ab6b-8d71cf1c11d7)
