### ISSUE TITLE
Two different types of decimal separators in my BACnet Integration

### ISSUE THREAD

**Issue by CV-Private** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#21]
My BACnet Integration shows two different types of decimal separators. Editable fields are shown with decimal point, whereas non-editable values are shown with a comma instead. 

This might be related to HA itself or to my PC settings, but since I don't have any other editable device in my HA, I'm only seeing it with BACnet objects. Any idea why?

![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/108861703/c3e5c9b1-4326-4fea-97cc-820b8dfb3fc8)

There is actually a setting for number formats in the User Profile in HA, therefore I think that it should be uniformly used everywhere in HA. 

![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/108861703/cf84ef81-93b8-40c8-b423-d4d90920f6b8)

My setting is Auto and the Language setting is German, so I would expect to see the comma as the decimal separator. It is shown like that in Dashboard cards for temperature settings, for example:

![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/108861703/cddb0f84-efdd-4e32-babf-bcd31b392dd3)

**Comment by CV-Private** [comment]
Ok, thanks! By the ways, I noticed it while trying to parse the state of a BACnet object. 

The (experimental) template below translates the presentValue of Entity VarApStatus to the text shown on the control panel of my heatpump. The template relies on strings, therefore the decimal separator matters.

![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/108861703/977b82f7-6140-4397-ac24-74c9b5d90d37)

![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/108861703/042be8c3-0bac-463f-a9e5-3515b20e3192)

The template works fine so far. Now I need to add all other possible states.

**Comment by Bepacom-Raalte** [comment]
I think internally it's all with dots, but I'm not the best at making templates so I wouldn't know for sure.
