### ISSUE TITLE
Can't get integration to work

### ISSUE THREAD

**Issue by BertPorter** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#23]
I have several BACnet devices. I would like to access some of their functionality on Home Assistant dashboards. Eventually I hope to access everything on them using Home Assistant.

I am able to connect to these devices using your Add-On.
<br>
<img width="1273" alt="Screenshot 2024-04-19 at 11 22 35 PM" src="https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/19476837/629b549a-2df1-4392-90fd-0b2028db9b8a">
<br>
I am not able to install your Integration.
<br>
<img width="462" alt="Screenshot 2024-04-19 at 11 20 12 PM" src="https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/19476837/2acb63d7-5165-4202-9490-6a4f7934b952">
<br>
Please advise.

**Comment by gioassio89** [comment]
did you configure integration with the ip address ok home assistant?
![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/6c1e9117-0492-4931-b376-fa3f42a269d5)

**Comment by GravySeal** [comment]
Hello, thank you for reporting the issue. 
I think it is add-on related, so could you maybe share the add-on logs with me? Preferably the one downloaded through the web UI.
Could you also share your Home Assistant logs so I know what happens with the integration just to be sure?

**Comment by BertPorter** [comment]
Resolved! 
I deleted from integration, add-on, and HACS. Reinstalled and it worked.
Thanks.

**Comment by GravySeal** [comment]
Awesome, great to hear! Glad you got it solved.
