### ISSUE TITLE
Size of home assistant backup 

### ISSUE THREAD

**Issue by gioassio89** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#24]
Hi, I've noticed a significant increase in the size of the Home Assistant backup images since I installed the Bepacom BACnet/IP Interface. On average, the backup file increases by 12MB every day. Today, it's almost 100MB, with more than half of that being from the file 97683af0_bacnetinterface_dev.tar.gz. Currently, I'm using version 1.4.1b6.
![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/b71bee2a-21e4-4053-8565-9326d8d2fb37)

Here's my configuration
![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/dd8433c2-33e1-4d91-a346-66dd933010c9)

**Comment by GravySeal** [comment]
How many entities do you get from your BACnet integration? If each entity is recording data, this does increase the database size, thus also the backup size. If you prefer smaller backup sizes, perhaps you should make exclusions in the [recorder](https://www.home-assistant.io/integrations/recorder/) integration.

**Comment by gioassio89** [comment]
Hi, currently I'm around 300:

![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/1bc53bf3-a921-40e0-b153-1e3e596ca135)

**Comment by gioassio89** [comment]
no i don't do any configuration in record integraiton, i will update you next week about bkp size!thanks!

**Comment by GravySeal** [comment]
How about it's size now? Did it stabilize or is it still ever growing?

**Comment by gioassio89** [comment]
Hello, the size of the backups is stable at 130 MB now. However, I've noticed a gradual increase in the amount of RAM being used: at system startup, the occupied RAM is about 950 MB, and I've noticed a daily increase of approximately 150 MB. It reached a maximum of almost 2 GB occupied, then I had to restart for an update. With 8 GB available, I'm not sure if this gradual increase is normal until reaching a certain limit or if this is directly related to this integration. Can I ask for your opinion?

**Comment by GravySeal** [comment]
This is the total system RAM usage? I'd say that's normal, as all the RAM that's not used is wasted RAM.
My Home Assistant OS has been running uninterrupted for almost 40 days now, and is currently using 4GB of the 6GB I gave it. 
As it's an OS, it can manage where it uses it's RAM for, and it'll free up space wherever it needs it most.

**Comment by Bepacom-Raalte** [comment]
I'll close this issue now since it seems solved.
