### ISSUE TITLE
HA Bacnet update killed communications

### ISSUE THREAD

**Issue by wamber2011** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#26]
Hello, I had been using this interface for the last month or so. After updating HA all my points get no data. I uninstalled everything and did a fresh install with the latest files and now all points data is greyed out with no data. The bacnet browser (red screen) can see all the devices.

Anyone else having similar issues?

![2024-04-29_21h24_23](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/156784122/3d1b7342-b6c8-4b2d-8071-86df01336101)

**Comment by GravySeal** [comment]
Hey @wamber2011 

Could you please provide me with logs downloaded through the web UI for the add-on, and logs from Home Assistant at Settings > System > Logs. On this page, press Load full logs to download a log file.
This way I'll have some information to go and look for the problem.

**Comment by Bepacom-Raalte** [comment]
Do you still have this issue or is it resolved?
