### ISSUE TITLE
error writing a boolean point

### ISSUE THREAD

**Issue by gioassio89** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#29]
hi! i recently update to last beta verison of the Bepacom EcoPanel BACnet Interface  and Bepacom BACnet/IP Interface Development Version (1.4.1b9) with te verion downloaded two month ago all works well,  with the last verions  i cant' write boolean point (see the error in the image below): 
![Immagine WhatsApp 2024-07-17 ore 21 39 12_604327c2](https://github.com/user-attachments/assets/a02af294-8b94-4e35-8d56-f5005c313908)
i can write enumerated and numeric point without any problem.
edit: with bepacom BACnet/IP Interface 0.2.1 and 1.4.1 i have no problem

**Comment by GravySeal** [comment]
Hey, thank you for notifying me!

I coincidentally detected this issue this evening as well. It's a problem with v0.2.2b5.
Could you try v0.2.2b6 to see if this issue has been resolved?

**Comment by gioassio89** [comment]
Hi! With v2.2b6 all works fine! Thanks a lot!

**Comment by GravySeal** [comment]
Great to hear! I'll mark this issue as done when this version is out of beta.

**Comment by gioassio89** [comment]
Ok, thanks a lot!

Il gio 18 lug 2024, 09:35 GravySeal ***@***.***> ha scritto:
